"""add channel and violation type

Revision ID: 3d6a5fac612f
Revises: 54832fde3607
Create Date: 2025-11-22 20:51:59.780333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6a5fac612f'
down_revision: Union[str, None] = '54832fde3607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('inspections', sa.Column('reported_violation_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'reported_violation_type')
    op.drop_column('inspections', 'channel')
    # ### end Alembic commands ###
