"""add triage fields

Revision ID: b2e90b7cf8c9
Revises: 3d6a5fac612f
Create Date: 2025-11-22 20:59:19.890466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e90b7cf8c9'
down_revision: Union[str, None] = '3d6a5fac612f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('violation_subtype', sa.String(), nullable=True))
    op.add_column('inspections', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('inspections', sa.Column('is_imminent_threat', sa.Boolean(), nullable=True))
    op.add_column('inspections', sa.Column('duplicate_of_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'inspections', 'inspections', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'duplicate_of_id')
    op.drop_column('inspections', 'is_imminent_threat')
    op.drop_column('inspections', 'severity')
    op.drop_column('inspections', 'violation_subtype')
    # ### end Alembic commands ###
