"""add inspection_comments table

Revision ID: c0b21b69bd25
Revises: 2f3e4d5c6b7a
Create Date: 2025-10-29 20:49:18.085854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'c0b21b69bd25'
down_revision: Union[str, None] = '2f3e4d5c6b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _index_exists(conn, index_name: str) -> bool:
    """Return True if the index already exists in the current schema."""
    result = conn.execute(sa.text("SELECT to_regclass(:name)"), {"name": index_name}).scalar()
    return result is not None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if 'image_analysis_logs' not in inspector.get_table_names():
        op.create_table(
            'image_analysis_logs',
            ...
        )

    if not _index_exists(bind, op.f('ix_app_settings_key')):
        op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)

    if not _index_exists(bind, op.f('ix_app_settings_audit_id')):
        op.create_index(op.f('ix_app_settings_audit_id'), 'app_settings_audit', ['id'], unique=False)

    if not _index_exists(bind, op.f('ix_chat_logs_thread_id')):
        op.create_index(op.f('ix_chat_logs_thread_id'), 'chat_logs', ['thread_id'], unique=False)

    op.drop_index('index_notifications_on_comment_id', table_name='notifications')
    op.create_foreign_key(None, 'notifications', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_index('index_notifications_on_comment_id', 'notifications', ['comment_id'], unique=False)
    op.drop_index(op.f('ix_chat_logs_thread_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_app_settings_audit_id'), table_name='app_settings_audit')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    # ### end Alembic commands ###
