"""Add review_later flag to comments

Revision ID: cedff70779f4
Revises: c0b21b69bd25
Create Date: 2025-11-13 10:32:15.304719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedff70779f4'
down_revision: Union[str, None] = 'c0b21b69bd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('review_later', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'review_later')
    # ### end Alembic commands ###
