"""add businesses.is_closed/opened_on/employee_count

Revision ID: fb1d50b069a7
Revises: 851cec9d964f
Create Date: 2025-09-23 11:08:48.616779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1d50b069a7'
down_revision: Union[str, None] = '851cec9d964f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
